"""baseline

Revision ID: bb7bf35a3be6
Revises: 
Create Date: 2026-07-22 13:13:23.697681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb7bf35a3be6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('bales_product_id'), table_name='bales')
    op.drop_index(op.f('bales_product_id_status'), table_name='bales')
    op.drop_index(op.f('bales_status'), table_name='bales')
    op.drop_table('bales')
    op.drop_table('orders')
    op.drop_index(op.f('link'), table_name='products')
    op.drop_index(op.f('link_10'), table_name='products')
    op.drop_index(op.f('link_11'), table_name='products')
    op.drop_index(op.f('link_12'), table_name='products')
    op.drop_index(op.f('link_13'), table_name='products')
    op.drop_index(op.f('link_14'), table_name='products')
    op.drop_index(op.f('link_15'), table_name='products')
    op.drop_index(op.f('link_16'), table_name='products')
    op.drop_index(op.f('link_17'), table_name='products')
    op.drop_index(op.f('link_18'), table_name='products')
    op.drop_index(op.f('link_19'), table_name='products')
    op.drop_index(op.f('link_2'), table_name='products')
    op.drop_index(op.f('link_20'), table_name='products')
    op.drop_index(op.f('link_21'), table_name='products')
    op.drop_index(op.f('link_22'), table_name='products')
    op.drop_index(op.f('link_23'), table_name='products')
    op.drop_index(op.f('link_24'), table_name='products')
    op.drop_index(op.f('link_25'), table_name='products')
    op.drop_index(op.f('link_26'), table_name='products')
    op.drop_index(op.f('link_27'), table_name='products')
    op.drop_index(op.f('link_28'), table_name='products')
    op.drop_index(op.f('link_29'), table_name='products')
    op.drop_index(op.f('link_3'), table_name='products')
    op.drop_index(op.f('link_30'), table_name='products')
    op.drop_index(op.f('link_31'), table_name='products')
    op.drop_index(op.f('link_32'), table_name='products')
    op.drop_index(op.f('link_33'), table_name='products')
    op.drop_index(op.f('link_34'), table_name='products')
    op.drop_index(op.f('link_35'), table_name='products')
    op.drop_index(op.f('link_36'), table_name='products')
    op.drop_index(op.f('link_37'), table_name='products')
    op.drop_index(op.f('link_38'), table_name='products')
    op.drop_index(op.f('link_39'), table_name='products')
    op.drop_index(op.f('link_4'), table_name='products')
    op.drop_index(op.f('link_40'), table_name='products')
    op.drop_index(op.f('link_41'), table_name='products')
    op.drop_index(op.f('link_42'), table_name='products')
    op.drop_index(op.f('link_43'), table_name='products')
    op.drop_index(op.f('link_44'), table_name='products')
    op.drop_index(op.f('link_45'), table_name='products')
    op.drop_index(op.f('link_46'), table_name='products')
    op.drop_index(op.f('link_47'), table_name='products')
    op.drop_index(op.f('link_48'), table_name='products')
    op.drop_index(op.f('link_49'), table_name='products')
    op.drop_index(op.f('link_5'), table_name='products')
    op.drop_index(op.f('link_50'), table_name='products')
    op.drop_index(op.f('link_51'), table_name='products')
    op.drop_index(op.f('link_52'), table_name='products')
    op.drop_index(op.f('link_53'), table_name='products')
    op.drop_index(op.f('link_54'), table_name='products')
    op.drop_index(op.f('link_55'), table_name='products')
    op.drop_index(op.f('link_56'), table_name='products')
    op.drop_index(op.f('link_57'), table_name='products')
    op.drop_index(op.f('link_58'), table_name='products')
    op.drop_index(op.f('link_6'), table_name='products')
    op.drop_index(op.f('link_7'), table_name='products')
    op.drop_index(op.f('link_8'), table_name='products')
    op.drop_index(op.f('link_9'), table_name='products')
    op.drop_index(op.f('products_created_by'), table_name='products')
    op.drop_index(op.f('products_product_type_id'), table_name='products')
    op.drop_index(op.f('products_status'), table_name='products')
    op.drop_index(op.f('products_sub_category_id'), table_name='products')
    op.drop_index(op.f('products_supplier_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('supplierId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('images', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('subCategoryId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('oldPrice', mysql.FLOAT(), nullable=False),
    sa.Column('deletedAt', mysql.DATETIME(), nullable=True),
    sa.Column('relistPriceCapPercent', mysql.FLOAT(), nullable=True, comment='Max allowed markup % for re-list. Null = use global default.'),
    sa.Column('relistMinQuantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Min buyable quantity for re-list offers. Null = use global default.'),
    sa.Column('productTypeId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='Product type within the subcategory (e.g. Phone, Smart Watch under Smart Devices).'),
    sa.Column('platform', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True, comment='Source/crawled product URL; unique when set (app-enforced where required).'),
    sa.Column('createdBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Admin user ID who created the product (e.g. via save-crawled).'),
    sa.Column('currency', mysql.VARCHAR(length=10), server_default=sa.text("'¥'"), nullable=True, comment='Currency symbol / code for the product price (e.g. ¥, $, ₦).'),
    sa.Column('productAttributes', mysql.LONGTEXT(), nullable=True, comment='JSON product attributes/spec metadata (stored as string; parsed on read).'),
    sa.Column('packageInfo', mysql.LONGTEXT(), nullable=True, comment='JSON package metadata (stored as string; parsed on read).'),
    sa.Column('rate', mysql.FLOAT(), nullable=True, comment='Product rating score from source marketplace.'),
    sa.Column('positiveFeedbackRate', mysql.FLOAT(), nullable=True, comment='Positive feedback percentage from source marketplace.'),
    sa.Column('reviewsNumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Number of product reviews on source marketplace.'),
    sa.Column('prices', mysql.LONGTEXT(), nullable=True, comment='JSON array of price objects (stringify on save; parse on read).'),
    sa.Column('evaluatePanelSummary', mysql.LONGTEXT(), nullable=True, comment='JSON evaluate panel summary (stringify on save; parse on read).'),
    sa.Column('shippingFee', mysql.FLOAT(), nullable=True, comment='Per-unit shipping fee (e.g. total shipping fee divided by quantity).'),
    sa.Column('moq', mysql.FLOAT(), nullable=True, comment='Minimum order quantity.'),
    sa.Column('isSpecial', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('originalPrice', mysql.FLOAT(), nullable=True, comment="Supplier's original price before markup — used for margin/cost tracking."),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('products_supplier_id'), 'products', ['supplierId'], unique=False)
    op.create_index(op.f('products_sub_category_id'), 'products', ['subCategoryId'], unique=False)
    op.create_index(op.f('products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('products_product_type_id'), 'products', ['productTypeId'], unique=False)
    op.create_index(op.f('products_created_by'), 'products', ['createdBy'], unique=False)
    op.create_index(op.f('link_9'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_8'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_7'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_6'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_58'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_57'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_56'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_55'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_54'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_53'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_52'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_51'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_50'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_5'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_49'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_48'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_47'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_46'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_45'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_44'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_43'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_42'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_41'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_40'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_4'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_39'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_38'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_37'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_36'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_35'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_34'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_33'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_32'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_31'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_30'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_3'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_29'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_28'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_27'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_26'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_25'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_24'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_23'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_22'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_21'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_20'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_2'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_19'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_18'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_17'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_16'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_15'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_14'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_13'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_12'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_11'), 'products', ['link'], unique=True)
    op.create_index(op.f('link_10'), 'products', ['link'], unique=True)
    op.create_index(op.f('link'), 'products', ['link'], unique=True)
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('request_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('merchant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('items', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('initial_price', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('platform', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('otp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('order_from', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fifthPicture', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('fourthPicture', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estemate_cost', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('initial_estemate_cost', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('merchantSlug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('delivery_days', mysql.INTEGER(display_width=11), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('modify_price', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modify_type', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('free_delivery', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('estemate_modify', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('estemate_modify_type', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('extra_changes_reference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('extra_charge_status', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('modify_by', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('selected_color', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('selected_size', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sku_attr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('sku_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('logistics_service_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('push_to_delivery', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tracking_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pushed_on', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bales',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filled', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('slot', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filledSlot', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('oldPrice', mysql.FLOAT(), nullable=False),
    sa.Column('baleId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('OPEN', 'FILLED', 'EXPIRED', 'LOCKED', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED'), server_default=sa.text("'OPEN'"), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('endIn', mysql.DATETIME(), nullable=True),
    sa.Column('deliveryFee', mysql.FLOAT(), nullable=False),
    sa.Column('totalDeliveryFee', mysql.FLOAT(), nullable=False),
    sa.Column('shipmentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), server_default=sa.text("'¥'"), nullable=True, comment='Currency symbol / code for the bale price (e.g. ¥, $, ₦). Inherited from product on creation.'),
    sa.Column('originalPrice', mysql.FLOAT(), nullable=True, comment="Supplier's original price before markup — used for margin/cost tracking"),
    sa.Column('createdBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='FK to adminUsers – the admin who created this bale'),
    sa.Column('startedAt', mysql.DATETIME(), nullable=True, comment='When the bale pool window started; defaults to creation time.'),
    sa.Column('isSpecial', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Whether this bale is a special / featured offer.'),
    sa.Column('prices', mysql.LONGTEXT(), nullable=True, comment='JSON array of { price, min, max } tiers by slot index (stringify on save; parse on read).'),
    sa.Column('restartedCount', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Increments on each successful POST /bale/:id/restart.'),
    sa.Column('cycle', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Pool cycle; increments on each restart.'),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], name=op.f('bales_ibfk_1'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('bales_status'), 'bales', ['status'], unique=False)
    op.create_index(op.f('bales_product_id_status'), 'bales', ['productId', 'status'], unique=False)
    op.create_index(op.f('bales_product_id'), 'bales', ['productId'], unique=False)
    # ### end Alembic commands ###
